version: 2

models:
  - name: stg_customers
    description: "Cleaned customers from raw.customers"
    columns:
      - name: customer_id
        tests: [not_null, unique]
      - name: email
        tests: [not_null]

  - name: stg_orders
    description: "Cleaned orders from raw.orders"
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null]

  - name: stg_payments
    description: "Cleaned payments from raw.payments"
    columns:
      - name: payment_id
        tests: [not_null, unique]
      - name: order_id
        tests: [not_null]

  - name: int_order_payments
    description: "Aggregated payments per order"
    columns:
      - name: order_id
        tests: [not_null, unique]

  - name: dim_customers
    description: "Customer dimension"
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: fct_orders
    description: "Order fact table with payments info"
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null]